# Generated by Django 4.2.7 on 2023-12-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('tier', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CombatList',
            fields=[
                ('creature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='combat_list', serialize=False, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('gold', models.PositiveSmallIntegerField()),
                ('wins', models.PositiveSmallIntegerField()),
                ('loss', models.PositiveSmallIntegerField()),
                ('round', models.PositiveSmallIntegerField()),
                ('tier', models.PositiveSmallIntegerField()),
                ('tier_cost', models.PositiveSmallIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data', serialize=False, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('max_health', models.PositiveSmallIntegerField()),
                ('defense', models.SmallIntegerField()),
                ('attack', models.SmallIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='creature', serialize=False, to='api.player')),
                ('items', models.ManyToManyField(blank=True, related_name='creatures', to='api.item')),
            ],
        ),
    ]
