# Generated by Django 4.2.7 on 2023-12-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='store_list',
            field=models.ManyToManyField(blank=True, to='api.item'),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='gold',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='round',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='tier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='tier_cost',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
