# Generated by Django 4.2.7 on 2023-12-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_creature_items_creatureitemcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='items',
            field=models.ManyToManyField(blank=True, through='api.CreatureItemCount', to='api.item'),
        ),
        migrations.AlterField(
            model_name='creatureitemcount',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creature'),
        ),
    ]
