# Generated by Django 4.2.7 on 2023-12-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_creature_items_alter_creatureitemcount_creature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureitemcount',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='api.creature'),
        ),
    ]
