# Generated by Django 4.2.7 on 2023-12-13 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_creature_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatlist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combatlist',
            name='creature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_list', to='api.creature'),
        ),
    ]
