# Generated by Django 4.2.7 on 2023-12-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_combatlist_id_alter_combatlist_creature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='store_list',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='store_list',
            field=models.JSONField(default=[]),
        ),
    ]
