# Generated by Django 4.2.7 on 2023-12-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_gamedata_store_list_gamedata_store_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='store_list',
            field=models.JSONField(default=list),
        ),
    ]
