# Generated by Django 4.2.7 on 2023-12-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gamedata_store_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='icon',
            field=models.CharField(default='TODO', max_length=100),
            preserve_default=False,
        ),
    ]
