# Generated by Django 4.2.7 on 2023-12-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('user', '0004_alter_user_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='api.player'),
        ),
    ]
